Delete auto-push.yml
travellings-link/travellings pull request #1177
Opened 2022-08-30 09:29 UTC by qystudio0

2022-08-30 09:36 UTC, HAHH9527 commented
是要取消自动部署吗

2022-08-30 15:18 UTC, HAHH9527 requested changes
改UI我没有任何意见
但是新站的添加审核全在现有repo
cn站点独立使用新repo会导致站点列表不同步

2022-08-30 15:35 UTC, HAHH9527 commented
提出一个方案
- 此库仅保留站点列表和审批等站点列表相关功能
- 前端另建 repo 命名参考 `travellings_website`
- 前端 repo 如要做两个版本，那么写在不同分支中
- 目前情况，站点审核几乎每天都会有，鉴于此情况，我提出下面两个 action 部署方案，也可以讨论有没有其他合适的方法
> 1. 此 repo 触发，触发时拉取前端 repo 同时部署
> 2. 分开触发，此 repo 仅覆盖站点列表，前端 repo 仅覆盖前端页面
- 后端开使开发后，由后端主导开发人员自行建库

2022-08-30 15:35 UTC, HAHH9527 commented
@A7103

2022-08-31 00:14 UTC, qystudio0 commented
等测试完成双分支将会合并

2022-08-31 02:41 UTC, HAHH9527 commented
你需要测试什么内容

2022-08-31 02:44 UTC, A7103 commented
关于两个站点的具体情况我并不太清楚，但是好像是要重构项目？提两个方案：
1. 在原有的repo的master分支基础上创建新的开发分支，并不断merge 最新的master以避免代码冲突，之后部署到一个测试的域名上小规模使用（？）并测试。
2. 完全独立的两个repo，重构代码的repo可以先加入一些mock的数据进行页面开发，之后再将现在`travellings-link`中的数据迁移过去

---
> > 1. 此 repo 触发，触发时拉取前端 repo 同时部署
> > 2. 分开触发，此 repo 仅覆盖站点列表，前端 repo 仅覆盖前端页面.

>后端开使开发后，由后端主导开发人员自行建库

我的建议是前后端不要放在同一个仓库里，做到前后端分离，只通过接口通讯
- `travellings-website` - FE repo
- `travellings-services` - BE repo

两个repo都独立部署开发(最好都是用image的形式)，这样可以从根源上避免出现一些问题：
- 如果部署时掺杂着FE和BE的代码，那么git的工作树几乎都是乱的，难以溯源；
- 因为在同一个仓库，所以**可能会**因为目录结构而影响到一些工具（列如proto-gen等）的自动生成。
- 代码仓库可能会过大？部署时间变长？我只是修改前端界面但是却要一起部署后端？

2022-08-31 02:52 UTC, A7103 commented
另外推荐前后端使用[Protobuf](https://developers.google.com/protocol-buffers)通讯，而不是Json

2022-08-31 02:59 UTC, HAHH9527 commented
@qystudio0 如果你要用cn站点单独做新版UI测试可以使用 @A7103 提出的方案
> 在原有的repo的master分支基础上创建新的开发分支，并不断merge 最新的master以避免代码冲突，之后部署到一个测试的域名上小规模使用（？）并测试。

2022-08-31 13:42 UTC, qystudio0 commented
这是一个简单的测试，在明天将会删除本仓库中的前端代码，仅保留assets，审核组维护js即可

2022-08-31 14:48 UTC, HAHH9527 commented
> 这是一个简单的测试

这是一个什么测试？

> 在明天将会删除本仓库中的前端代码，仅保留assets，审核组维护js即可

请在新前端重构完成后再删除此repo中的前端代码。
换一种更详细的说法：请在新前端引用此repo中的成员列表后再对此repo中的前端代码进行删除。

2022-09-02 03:46 UTC, HAHH9527 commented
如果你只是想关掉cn的自动部署，删除这几行
```yml
  push:
    branches: 
      - master
```
其他的问题，请先理清楚逻辑，拿出完整方案，而不是转手交给其他人解决冲突

2022-09-02 03:46 UTC, closed without merging