🐋[Chore] 就统计事项进行修改
travellings-link/travellings pull request #1631
Opened 2023-08-04 02:58 UTC by linlinzzo

2023-08-04 06:09 UTC, Big-Cake-jpg requested changes
Cloudflare Web Analytics 没有 Umami 所具有的一些数据，而且只能统计通过 Cloudflare CDN 接受的请求。

2023-08-04 06:19 UTC, linlinzzo commented
> Cloudflare Web Analytics 没有 Umami 所具有的一些数据，而且只能统计通过 Cloudflare CDN 接受的请求。

其统计代码已经在源服务器部署。

2023-08-10 06:55 UTC, jiangmiemie commented
我们目前需要统计的主要是哪些？

2023-08-11 07:43 UTC, jiangmiemie commented
建议使用阿里云自带分析工具，减少不必要的跳转

2023-08-11 07:43 UTC, closed without merging